// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MRPReactApp.Models;

public partial class Blank
{
    public int Id { get; set; }

    public int Material { get; set; }

    public int? Lenght { get; set; }

    public int? Width { get; set; }

    public decimal Weight { get; set; }

    public virtual ICollection<DetailComposition> DetailComposition { get; set; } = new List<DetailComposition>();

    public virtual Material MaterialNavigation { get; set; }
}