// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MRPReactApp.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string Inn { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Contact { get; set; }

    public virtual ICollection<OrderProduct> OrderProduct { get; set; } = new List<OrderProduct>();
}