// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MRPReactApp.Models;

public partial class DetailComposition
{
    public int Id { get; set; }

    public int Product { get; set; }

    public int Blank { get; set; }

    public virtual Blank BlankNavigation { get; set; }

    public virtual Product ProductNavigation { get; set; }
}