// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MRPReactApp.Models;

public partial class MarkSteel
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Material> Material { get; set; } = new List<Material>();
}