// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MRPReactApp.Models;

public partial class OrderComposition
{
    public int Id { get; set; }

    public int OrderProduct { get; set; }

    public int Product { get; set; }

    public int Quantity { get; set; }

    public virtual OrderProduct OrderProductNavigation { get; set; }

    public virtual Product ProductNavigation { get; set; }
}