// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MRPReactApp.Models;

public partial class OrderProduct
{
    public int Id { get; set; }

    public string OrderNumber { get; set; }

    public DateTime OrderDate { get; set; }

    public DateTime? ExecutionDate { get; set; }

    public int Customer { get; set; }

    public virtual Customer CustomerNavigation { get; set; }

    public virtual ICollection<OrderComposition> OrderComposition { get; set; } = new List<OrderComposition>();

    public virtual ICollection<PlanComposition> PlanComposition { get; set; } = new List<PlanComposition>();
}