// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MRPReactApp.Models;

public partial class PlanComposition
{
    public int Id { get; set; }

    public int PlanProduct { get; set; }

    public int OrderProduct { get; set; }

    public virtual OrderProduct OrderProductNavigation { get; set; }

    public virtual PlanProduct PlanProductNavigation { get; set; }
}