// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MRPReactApp.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int Type { get; set; }

    public int? Kind { get; set; }

    public bool? Purchase { get; set; }

    public virtual ICollection<DetailComposition> DetailComposition { get; set; } = new List<DetailComposition>();

    public virtual ProductKind KindNavigation { get; set; }

    public virtual ICollection<OrderComposition> OrderComposition { get; set; } = new List<OrderComposition>();

    public virtual ICollection<Specification> SpecificationComponentNavigation { get; set; } = new List<Specification>();

    public virtual ICollection<Specification> SpecificationProductNavigation { get; set; } = new List<Specification>();

    public virtual ProductType TypeNavigation { get; set; }
}